
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 123
#define YY_END_OF_BUFFER 124
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[468] =
    {   0,
        0,    0,  124,  122,  121,  121,  109,  122,   73,  115,
      108,  122,  103,  104,  113,  112,  100,  111,  107,  114,
       64,   63,  101,   97,  116,  102,  117,  120,   61,   61,
      105,  106,  118,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   98,
      119,   99,  110,  121,   96,    0,   72,    0,    0,   82,
       99,   91,   83,    0,    0,   80,   88,   78,   89,   79,
       90,    0,   67,    1,    2,   81,   68,   64,    0,    0,
       64,   64,    0,   64,   63,   63,   63,   63,  106,   98,
      105,   87,   93,   95,   94,   86,   61,    0,    0,   84,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   11,   61,   61,   61,   61,
       61,   61,   19,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   85,   92,   72,    0,    0,
        0,    0,    0,   65,    0,    0,   75,    0,   67,    2,
        0,   68,    0,   66,   64,   64,   64,   64,    0,   62,
       63,   63,   63,   63,   77,   76,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   17,   61,   61,   23,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,    0,    0,    0,    0,    0,    0,
       67,    0,   68,   66,   64,    0,    0,   62,    0,   62,
       62,   63,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,    4,   61,    6,    7,   61,   61,   61,   61,   13,
       14,   61,   61,   18,   61,   34,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   47,   61,
       61,    0,    0,    0,    0,    0,    0,    0,   62,   62,
        0,   69,   62,   62,   61,   61,   53,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,    5,    8,   61,   61,   61,   61,
       16,   61,   61,   61,   61,   38,   61,   61,   61,   61,
       61,   61,   45,   61,   61,   49,    0,    0,   70,    0,
       71,   69,   62,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       24,   61,   61,   61,   61,   61,   61,   12,   15,   20,
       61,   61,   37,   39,   40,   41,   42,   43,   61,   61,
       61,    0,   70,   71,   61,   61,   52,   61,   61,   61,
       61,   61,   61,   28,   61,   61,   61,   61,   61,   25,

       26,   27,   61,   61,   61,   61,   61,   10,   61,   61,
       44,   61,   61,   74,   50,   51,   54,   55,   61,   61,
       61,   61,   61,   61,   61,   60,   61,    3,   61,   61,
       61,    9,   35,   36,   46,   48,   61,   57,   61,   61,
       29,   61,   61,   61,    3,    3,   30,   61,   61,   56,
       61,   61,   22,   31,   21,   32,   61,   61,   61,   61,
       61,   61,   33,   61,   59,   58,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   23,   25,   26,   27,   28,   29,
       30,   31,   32,    1,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   40,   40,   42,   40,   43,   40,   44,
       40,   40,   45,   46,   47,   40,   40,   48,   40,   40,
       49,   50,   51,   52,   53,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   40,   63,   64,   65,   66,
       67,   68,   40,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,   79,   80,   81,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    6,    6,    6,    6,    7,    5,    8,    8,
        8,    9,    8,    8,    8,    8,    8,    8,    1,    1,
        1,    1,    8,    6,    6,    6,    6,    7,    5,    8,
        8,    8,    8,    9,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[485] =
    {   0,
        0,    0,  962,  963,   80,   82,  931,   81,  898,   57,
       81,  909,  963,  963,  928,   77,  963,   78,   76,   93,
      116,  176,  926,  963,   97,  926,   82,  963,    0,  109,
      963,  963,  925,  116,  882,  884,   61,   58,   55,   39,
      885,   86,  884,  892,  104,  873,  151,  881,  886,  963,
      103,  963,  963,  141,  963,  143,  165,  244,  880,  963,
      963,  963,  963,  137,  315,  963,  963,  963,  963,  963,
      963,  929,  147,  963,    0,  963,  166,   72,  263,  330,
      167,  168,  928,  107,    0,  173,  174,  172,  963,  963,
      963,  913,  963,  963,  963,  912,    0,  172,  884,  963,

      119,  858,  855,  863,  855,  850,  845,  854,  234,  841,
      853,  840,  853,  840,  846,  830,  831,  828,  823,  826,
      823,  802,    0,  157,  804,  171,  801,  166,  181,  793,
      786,  840,  111,  165,  777,  963,  963,  269,  833,  250,
      307,    0,  781,  963,  373,    0,  963,  385,  963,    0,
      406,  963,  415,  214,  186,  963,  794,  771,    0,  400,
      223,  963,  792,  769,  963,  963,  770,  764,  763,  764,
      762,  773,  757,  771,  755,  190,  765,  197,  756,  752,
      749,  758,  760,  750,  762,  757,  741,  189,  755,  753,
      749,  741,  747,  750,    0,  736,  740,    0,  741,  738,

      728,  726,  728,  730,  737,  717,  715,  715,  727,  717,
      721,  725,  727,  716,  438,  484,  701,  461,  535,  472,
      259,  505,  302,  963,  963,  264,  278,  317,  582,  250,
      311,  963,  698,  692,  692,  687,  696,  693,  694,  680,
      692,  691,  679,  691,  676,  679,  296,  690,  686,  680,
      685,    0,  677,    0,    0,  668,  676,  665,  672,    0,
        0,  666,  663,    0,  663,    0,  658,  658,  657,  654,
      666,  656,  660,  665,  664,  662,  652,  657,    0,  645,
      657,  256,    0,  642,  362,    0,  596,  610,  315,  963,
      556,  407,  665,  642,  639,  642,    0,  639,  633,  639,

      629,  637,  630,  624,  623,  614,  606,  619,  612,  427,
      613,  616,  601,  599,    0,    0,  603,  604,  609,  600,
        0,  607,  593,  601,  596,    0,  604,  601,  602,  586,
      595,  569,    0,  560,  562,    0,  556,  619,  524,  628,
      617,  963,  963,  309,  556,  552,  537,  532,  524,  531,
      529,  520,  513,  495,  508,  510,  486,  527,  530,  527,
        0,  483,  493,  490,  478,  465,  465,    0,    0,    0,
      477,  477,    0,    0,    0,    0,    0,    0,  473,  458,
      451,  456,  963,  963,  443,  453,    0,  426,  444,  445,
      418,  433,  425,    0,  413,  408,  421,  421,  415,    0,

        0,    0,  415,  403,  411,  394,  397,    0,  385,  382,
        0,  393,  364,  963,    0,    0,    0,    0,  351,  352,
      363,  351,  350,  355,  338,    0,  348,  681,  335,  321,
      324,    0,    0,    0,    0,    0,  303,    0,  308,  310,
        0,  317,  308,  315,    0,  762,    0,  278,  255,    0,
      210,  221,    0,    0,    0,    0,  193,  188,  132,  108,
       60,   53,    0,   20,    0,    0,  963,  843,  852,  857,
      862,  871,  877,  880,  883,  886,  891,  894,  899,  904,
      909,  914,  923,  932
    } ;

static const flex_int16_t yy_def[485] =
    {   0,
      467,    1,  467,  467,  467,  467,  467,  468,  467,  467,
      467,  469,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  470,  470,
      467,  467,  467,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  467,
      467,  467,  467,  467,  467,  468,  467,  467,  467,  467,
      467,  467,  467,  469,  467,  467,  467,  467,  467,  467,
      467,  467,  471,  467,  472,  467,  471,   21,  467,  467,
      467,  467,  473,  467,   22,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  470,  468,  469,  467,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  467,  467,  467,  467,  467,
      468,  474,  467,  467,  469,  475,  467,  467,  467,  472,
      467,  467,  467,  476,  467,  467,  467,  467,  477,  473,
      467,  467,  467,  467,  467,  467,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  468,  468,  467,  469,  469,  467,
      478,  467,  479,  467,  467,  477,  477,  467,  467,  467,
      467,  467,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  468,  216,  467,  469,  219,  467,  467,  467,  467,
      467,  480,  467,  467,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  467,  467,  481,  467,
      482,  467,  467,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  467,  467,  467,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  467,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  483,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  484,  483,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,    0,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467
    } ;

static const flex_int16_t yy_nxt[1045] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   23,   24,   25,   26,
       27,   28,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   30,   29,   29,   29,   29,   30,   29,   31,    4,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       29,   42,   29,   43,   29,   29,   29,   29,   44,   45,
       46,   47,   48,   49,   29,   29,   29,   50,   51,   52,
       53,   54,   54,   54,   54,   57,   60,   61,   62,   67,
      466,   72,   69,   73,   73,   73,   73,   73,   73,   73,

       73,   73,  120,   90,   74,  121,   68,   70,   71,   75,
       63,   95,   96,   98,  112,  115,  465,   99,  117,  467,
      118,  113,   76,   91,  116,   92,   93,  114,  464,  119,
       58,   77,  136,   78,   78,   78,   78,   78,   78,   78,
       79,   79,   54,   54,  123,  144,  467,   57,  101,  102,
      103,  124,   80,  156,  104,   98,  105,   81,  106,   99,
      107,  108,   82,   83,  127,  128,  138,  138,  109,   98,
      155,  463,  210,   80,  129,  132,   57,  130,  156,   84,
      211,  137,  167,  148,  149,  462,   65,   82,  149,  168,
       83,   77,   58,   85,   85,   85,   85,   85,   85,   85,

       85,   85,  151,  152,  148,  149,  139,  152,  155,  157,
      149,  139,   80,  156,  161,  163,  133,   86,  162,  162,
      197,   58,   87,  151,  152,  204,  212,  198,  213,  152,
      200,  158,  156,   80,  206,  161,  140,  164,  156,   88,
      201,  202,  205,  162,  162,  461,  242,   87,   56,  207,
      245,  224,   56,  243,   98,  224,  460,  156,  256,  257,
       57,  141,  141,  141,  141,  141,  141,  141,  246,  162,
      138,  138,  224,   98,  139,   56,  459,  224,   77,  458,
       79,   79,   79,   79,   79,   79,   79,   79,   79,  176,
      177,  293,  178,   56,  162,  179,  149,   56,   56,   80,

      149,  180,   56,  181,  182,   58,  183,  287,  457,   56,
      139,   57,   56,  294,   56,  139,   56,  149,  142,   64,
       80,  288,  149,   64,  215,  215,  215,  215,  215,  215,
      215,  287,  145,  145,  145,  145,  145,  145,  145,  152,
      140,  456,  153,  152,  153,  288,   64,  154,  154,  154,
      154,  154,  154,  154,  154,  154,   58,  290,  289,  309,
      152,  290,  385,  290,   64,  152,  310,  455,   64,   64,
      144,  454,  453,   64,  289,  386,  452,  451,  450,  449,
       64,  144,  290,   64,  448,   64,  290,   64,  290,  146,
      218,  218,  218,  218,  218,  218,  218,  220,  447,  220,

      444,  443,  221,  221,  221,  221,  221,  221,  221,  221,
      221,   65,  442,  441,  440,  227,  439,  438,  222,  437,
      222,  436,   65,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  228,   57,  229,  342,  358,  230,  359,  342,  435,
      360,  361,  434,  433,  432,  282,  282,  282,  282,  282,
      282,  282,  431,  231,  430,  342,  429,  229,  428,  144,
      342,  230,  427,  426,  425,  424,  423,  422,  285,  285,
      285,  285,  285,  285,  285,  421,  420,   58,   57,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  419,  418,

      417,  283,  283,  283,  283,  283,  283,  283,  283,  283,
       65,  416,  415,  414,  413,  412,  283,  283,  283,  283,
      283,  283,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  411,  410,   58,  409,  408,  407,  283,  283,  283,
      283,  283,  283,  144,  406,  405,  404,  403,  402,  401,
      400,  399,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  383,  398,  397,  396,  383,  395,  286,  286,  286,
      286,  286,  286,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  383,  394,   65,  393,  392,  383,  286,  286,
      286,  286,  286,  286,  291,  391,  291,  390,  389,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  338,  388,
      338,  387,  382,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  340,  381,  340,  380,  379,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  384,  378,  377,  376,  384,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  357,  356,  384,  355,  354,  353,  352,
      384,  445,  445,  351,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  350,  349,

      348,  347,  346,  345,  344,  343,  343,  445,  445,  445,
      445,  445,  445,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  445,
      445,  445,  445,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  445,  445,
      445,  445,  445,  445,  284,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  445,  445,
      445,  445,  445,  445,  272,  271,  270,  269,  268,  267,

      266,  265,  264,  263,  262,  261,  260,  259,  258,  255,
      445,  445,  445,  445,  254,  253,  252,  251,  250,  249,
      248,  247,  244,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  232,  225,  225,  217,   98,  214,  445,
      445,  445,  445,   56,   98,   56,   56,   56,   56,   56,
       56,   56,   64,  209,  208,   64,   64,   64,   64,   64,
       64,   97,   97,   97,   97,   97,   73,  203,   73,  199,
       73,  150,  196,  150,  150,  150,  150,  150,  150,  150,
      160,  160,  160,  160,  216,  216,  216,  219,  219,  219,
      154,  195,  194,  193,  154,  226,  226,  226,  221,  192,

      191,  190,  221,  223,  189,  188,  187,  223,  292,  186,
      185,  184,  292,  339,  175,  174,  173,  339,  341,  172,
      171,  170,  341,  446,  169,  446,  446,  446,  446,  446,
      446,  446,  445,   65,  445,  445,  445,  445,  445,  445,
      445,  166,  165,  159,  147,  143,  135,  134,  131,  126,
      125,  122,  111,  110,  100,   94,   89,   66,   65,   59,
       55,  467,    3,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467
    } ;

static const flex_int16_t yy_chk[1045] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    6,    6,    8,   10,   10,   11,   16,
      464,   19,   18,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   40,   25,   20,   40,   16,   18,   18,   20,
       11,   27,   27,   30,   37,   38,  462,   30,   39,   78,
       39,   37,   20,   25,   38,   25,   25,   37,  461,   39,
        8,   21,   51,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   54,   54,   42,   64,   78,   56,   34,   34,
       34,   42,   21,   84,   34,   47,   34,   21,   34,   47,
       34,   34,   21,   21,   45,   45,   57,   57,   34,   57,
       84,  460,  133,   21,   45,   47,   98,   45,   84,   21,
      133,   51,  101,   73,   73,  459,   64,   21,   73,  101,
       21,   22,   56,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   77,   77,   73,   73,   57,   77,   81,   82,
       73,   57,   22,   81,   86,   87,   47,   22,   88,   86,
      124,   98,   22,   77,   77,  128,  134,  124,  134,   77,
      126,   82,  155,   22,  129,   88,   57,   87,   81,   22,
      126,  126,  128,   88,   86,  458,  176,   22,   58,  129,
      178,  154,   58,  176,  140,  154,  457,  155,  188,  188,
      282,   58,   58,   58,   58,   58,   58,   58,  178,  161,
      138,  138,  154,  138,  140,   58,  452,  154,   79,  451,
       79,   79,   79,   79,   79,   79,   79,   79,   79,  109,
      109,  230,  109,   58,  161,  109,  221,   58,   58,   79,

      221,  109,   58,  109,  109,  282,  109,  226,  449,   58,
      138,  141,   58,  230,   58,  138,   58,  221,   58,   65,
       79,  227,  221,   65,  141,  141,  141,  141,  141,  141,
      141,  226,   65,   65,   65,   65,   65,   65,   65,  223,
      138,  448,   80,  223,   80,  227,   65,   80,   80,   80,
       80,   80,   80,   80,   80,   80,  141,  231,  228,  247,
      223,  289,  344,  228,   65,  223,  247,  444,   65,   65,
      285,  443,  442,   65,  231,  344,  440,  439,  437,  431,
       65,  145,  231,   65,  430,   65,  289,   65,  228,   65,
      145,  145,  145,  145,  145,  145,  145,  148,  429,  148,

      427,  425,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  285,  424,  423,  422,  160,  421,  420,  151,  419,
      151,  413,  145,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  160,  215,  160,  292,  310,  160,  310,  292,  412,
      310,  310,  410,  409,  407,  215,  215,  215,  215,  215,
      215,  215,  406,  160,  405,  292,  404,  160,  403,  218,
      292,  160,  399,  398,  397,  396,  395,  393,  218,  218,
      218,  218,  218,  218,  218,  392,  391,  215,  216,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  390,  389,

      388,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      218,  386,  385,  382,  381,  380,  216,  216,  216,  216,
      216,  216,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  379,  372,  216,  371,  367,  366,  216,  216,  216,
      216,  216,  216,  219,  365,  364,  363,  362,  360,  359,
      358,  357,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  339,  356,  355,  354,  339,  353,  219,  219,  219,
      219,  219,  219,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  339,  352,  219,  351,  350,  339,  219,  219,
      219,  219,  219,  219,  229,  349,  229,  348,  347,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  287,  346,
      287,  345,  337,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  288,  335,  288,  334,  332,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  341,  331,  330,  329,  341,  328,
      327,  325,  324,  323,  322,  320,  319,  318,  317,  314,
      313,  312,  311,  309,  308,  341,  307,  306,  305,  304,
      341,  428,  428,  303,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  302,  301,

      300,  299,  298,  296,  295,  294,  293,  428,  428,  428,
      428,  428,  428,  284,  281,  280,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  265,  428,
      428,  428,  428,  263,  262,  259,  258,  257,  256,  253,
      251,  250,  249,  248,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  428,  428,
      428,  428,  446,  446,  217,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  446,  446,
      446,  446,  446,  446,  205,  204,  203,  202,  201,  200,

      199,  197,  196,  194,  193,  192,  191,  190,  189,  187,
      446,  446,  446,  446,  186,  185,  184,  183,  182,  181,
      180,  179,  177,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  164,  163,  158,  157,  143,  139,  135,  446,
      446,  446,  446,  468,  132,  468,  468,  468,  468,  468,
      468,  468,  469,  131,  130,  469,  469,  469,  469,  469,
      469,  470,  470,  470,  470,  470,  471,  127,  471,  125,
      471,  472,  122,  472,  472,  472,  472,  472,  472,  472,
      473,  473,  473,  473,  474,  474,  474,  475,  475,  475,
      476,  121,  120,  119,  476,  477,  477,  477,  478,  118,

      117,  116,  478,  479,  115,  114,  113,  479,  480,  112,
      111,  110,  480,  481,  108,  107,  106,  481,  482,  105,
      104,  103,  482,  483,  102,  483,  483,  483,  483,  483,
      483,  483,  484,   99,  484,  484,  484,  484,  484,  484,
      484,   96,   92,   83,   72,   59,   49,   48,   46,   44,
       43,   41,   36,   35,   33,   26,   23,   15,   12,    9,
        7,    3,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[124] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grammar.l"
#line 28 "grammar.l"
/* https://www.quut.com/c/ANSI-C-grammar-l-2011.html */
#include <stdio.h>

extern void yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static void comment(void);
// static int check_type(void);

void count(void);
void AddToScopeList(void);
void discard(void);
int check_type(char var[]);
#line 877 "lex.yy.c"
#line 878 "lex.yy.c"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "grammar.l"

#line 1094 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 468 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 963 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "grammar.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "grammar.l"
{ discard(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "grammar.l"
{ discard(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "grammar.l"
{ count(); return(AUTO); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "grammar.l"
{ count(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "grammar.l"
{   count();
                            if (CaseListUsed == NO)
                            {
                                Case = CreateList();	// LINKEDLISTS.H
                                CaseListUsed = YES;	// LINKEDLISTS.H
                            }
                            PushList(yylineno, Case);	// LINKEDLISTS.H
                            return(CASE);
                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "grammar.l"
{ count(); return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "grammar.l"
{ count(); return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 64 "grammar.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 65 "grammar.l"
{   count();
                            if (DefaultListUsed == NO)
                            {
                                Default = CreateList();	// LINKEDLISTS.H
                                DefaultListUsed = YES;	// LINKEDLISTS.H
                            }
                            PushList(yylineno, Default);	// LINKEDLISTS.H
                            return(DEFAULT);
                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 74 "grammar.l"
{   count();
                            if (DoListUsed == NO)
                            {
                                Do = CreateList();	// LINKEDLISTS.H
                                DoListUsed = YES;	// LINKEDLISTS.H
                            }
                            PushList(yylineno, Do);	// LINKEDLISTS.H
                            return(DO);
                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 83 "grammar.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 84 "grammar.l"
{ count(); return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 85 "grammar.l"
{ count(); return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 86 "grammar.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 87 "grammar.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 88 "grammar.l"
{   count();
                            if (ForListUsed == NO)
                            {
                                For = CreateList();	// LINKEDLISTS.H
                                ForListUsed = YES;	// LINKEDLISTS.H
                            }
                            PushList(yylineno, For);	// LINKEDLISTS.H
                            return(FOR);
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "grammar.l"
{ count(); return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "grammar.l"
{   count();
                            if (IfListUsed == NO)
                            {
                                If = CreateList();	// LINKEDLISTS.H
                                IfListUsed = YES;	// LINKEDLISTS.H
                            }
                            IfEnded++;
                            PushList(yylineno, If);	// LINKEDLISTS.H
                            return(IF);
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 108 "grammar.l"
{ count(); return(INLINE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 109 "grammar.l"
{ count(); return(INLINE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 110 "grammar.l"
{ count(); return(DECLSPEC); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 111 "grammar.l"
{ count(); return(INT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "grammar.l"
{ count(); return(__INT8); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "grammar.l"
{ count(); return(__INT16); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "grammar.l"
{ count(); return(__INT32); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "grammar.l"
{ count(); return(__INT64); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "grammar.l"
{ count(); return (__CDECL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "grammar.l"
{ count(); return (__CLRCALL); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "grammar.l"
{ count(); return (__STDCALL); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "grammar.l"
{ count(); return (__FASTCALL); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "grammar.l"
{ count(); return (__THISCALL); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 121 "grammar.l"
{ count(); return (__VECTORCALL); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 122 "grammar.l"
{ count(); return(LONG); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 123 "grammar.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 124 "grammar.l"
{ count(); return(RESTRICT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 125 "grammar.l"
{ count(); return(RETURN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 126 "grammar.l"
{ count(); return(SHORT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 127 "grammar.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 128 "grammar.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 129 "grammar.l"
{ count(); return(STATIC); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 130 "grammar.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 131 "grammar.l"
{   count();
                            if (SwitchListUsed == NO)
                            {
                                Switch = CreateList();	// LINKEDLISTS.H
                                SwitchListUsed = YES;	// LINKEDLISTS.H
                            }
                            PushList(yylineno, Switch);	// LINKEDLISTS.H
                            return(SWITCH);
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 140 "grammar.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 141 "grammar.l"
{ count(); return(UNION); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 142 "grammar.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 143 "grammar.l"
{ count(); return(VOID); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 144 "grammar.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "grammar.l"
{   count();
                            if (WhileListUsed == NO)
                            {
                                While = CreateList();	// LINKEDLISTS.H
                                WhileListUsed = YES;	// LINKEDLISTS.H
                            }
                            PushList(yylineno, While);	// LINKEDLISTS.H
                            return(WHILE);
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "grammar.l"
{ count(); return ALIGNAS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "grammar.l"
{ count(); return ALIGNOF; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 156 "grammar.l"
{ count(); return ATOMIC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 157 "grammar.l"
{ count(); return BOOL; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "grammar.l"
{ count(); return COMPLEX; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "grammar.l"
{ count(); return GENERIC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "grammar.l"
{ count(); return IMAGINARY; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "grammar.l"
{ count(); return NORETURN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "grammar.l"
{ count(); return STATIC_ASSERT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "grammar.l"
{ count(); return THREAD_LOCAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "grammar.l"
{ count(); return FUNC_NAME; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 166 "grammar.l"
{ count(); return check_type(yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return I_CONSTANT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 169 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return I_CONSTANT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return I_CONSTANT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 171 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return I_CONSTANT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 173 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return F_CONSTANT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 174 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return F_CONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 175 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return F_CONSTANT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 176 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return F_CONSTANT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 177 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return F_CONSTANT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 178 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return F_CONSTANT; }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 180 "grammar.l"
{ count(); yylval.id = malloc(strlen(yytext)+1); strcpy(yylval.id, yytext); return STRING_LITERAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 182 "grammar.l"
{ count(); discard(); 	 }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 183 "grammar.l"
{ discard();  }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 185 "grammar.l"
{ count(); return ELLIPSIS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 186 "grammar.l"
{ count(); return RIGHT_ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 187 "grammar.l"
{ count(); return LEFT_ASSIGN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 188 "grammar.l"
{ count(); return ADD_ASSIGN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 189 "grammar.l"
{ count(); return SUB_ASSIGN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 190 "grammar.l"
{ count(); return MUL_ASSIGN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 191 "grammar.l"
{ count(); return DIV_ASSIGN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 192 "grammar.l"
{ count(); return MOD_ASSIGN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 193 "grammar.l"
{ count(); return AND_ASSIGN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 194 "grammar.l"
{ count(); return XOR_ASSIGN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 195 "grammar.l"
{ count(); return OR_ASSIGN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 196 "grammar.l"
{ count(); return RIGHT_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 197 "grammar.l"
{ count(); return LEFT_OP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 198 "grammar.l"
{ count(); return INC_OP; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 199 "grammar.l"
{ count(); return DEC_OP; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 200 "grammar.l"
{ count(); return PTR_OP; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 201 "grammar.l"
{ count(); return AND_OP; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 202 "grammar.l"
{ count(); return OR_OP; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 203 "grammar.l"
{ count(); return LE_OP; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 204 "grammar.l"
{ count(); return GE_OP; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 205 "grammar.l"
{ count(); return EQ_OP; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 206 "grammar.l"
{ count(); return NE_OP; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 207 "grammar.l"
{ count(); return ';'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 208 "grammar.l"
{ count();
                            Push(yylineno);	// SCOPES.H
                            AddToScopeList();	// GRAMMAR.L
                            return('{');
                        }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 213 "grammar.l"
{ count(); return '}'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 214 "grammar.l"
{ count(); return ','; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 215 "grammar.l"
{ count(); return ':'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 216 "grammar.l"
{ count(); return '='; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 217 "grammar.l"
{ count(); return '('; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 218 "grammar.l"
{ count(); return ')'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 219 "grammar.l"
{ count(); return '['; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 220 "grammar.l"
{ count(); return ']'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 221 "grammar.l"
{ count(); return '.'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 222 "grammar.l"
{ count(); return '&'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 223 "grammar.l"
{ count(); return '!'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 224 "grammar.l"
{ count(); return '~'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 225 "grammar.l"
{ count(); return '-'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 226 "grammar.l"
{ count(); return '+'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 227 "grammar.l"
{ count(); return '*'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 228 "grammar.l"
{ count(); return '/'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 229 "grammar.l"
{ count(); return '%'; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 230 "grammar.l"
{ count(); return '<'; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 231 "grammar.l"
{ count(); return '>'; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 232 "grammar.l"
{ count(); return '^'; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 233 "grammar.l"
{ count(); return '|'; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 234 "grammar.l"
{ count(); return '?'; }
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
#line 236 "grammar.l"
{ count(); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 237 "grammar.l"
{ /* discard bad characters */ }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 239 "grammar.l"
ECHO;
	YY_BREAK
#line 1839 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 468 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 468 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 467);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 239 "grammar.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

void AddToScopeList(void)
{
/*
This function is user-defined & not available in original grammar file.
This function is called when '{' is parsed.
A new linked list for scopes is created and then this function is called.
If enteries have been added to the Parameters linked list these need to be
added to the new Scopes linked list just created and the parameter linked
list must be freed. This is to ensure that parameters are added to the
correct scope in the linked list.
*/

	/* variable declarations */
	char * varname;	// name of the variable
	int linenumber;	// find the line number 'varname' is in
	int param;	// is varname a parameter variable

	/* allocate space to the string variables used */
	varname = (char *) malloc(STRING_LIMIT);

	if (PListFirstUse == YES)		   // PARAMETERS.H
	{
		while( !IsEmptyPList(P) )	   // PARAMETERS.H
		{
			strcpy(varname, PopPList(P));	// PARAMETERS.H

			/* search for varname in Stack - if already there + param is YES */
			/* amend it at this scope to avoid it being confused for the same */
			/* variable as it belongs to another scope */
			linenumber =  ScopeSearch(varname);	/* SCOPES.H */
			param = ParameterSearch(varname);	/* SCOPES.H */

			if(linenumber == 0 && param == 1)
				AmendVar(varname, param);	/* SCOPES.H */
			PushVar(varname, YES);			/* SCOPES.H */
		}
		DisposePList(P);		   /* PARAMETERS.H */
		PListFirstUse = NO;		   /* PARAMETERS.H */
	}
}

void discard(void)
{
/*
  Discard Function.
 This file removes any lines beginning with the character '#'
 from the underlying C code file. Lines beginning with '#' may
 denote preprocessor #line directives, or comments, which do
 not have to be analysed.
*/
	char c;
	while ((c = (char)(input())) != '\n' && c != 0)	;
}

int column = 0;

void count(void)
{
/*
 Count Function - defined in original grammar file
 Unchanged here.
 This file maintains the tabs and spacing set in the underlying
 C code being analysed.
*/
	int i;
	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

}

int check_type(char var[])
{
    char * typename;
	typename = (char *) malloc(STRING_LIMIT);
	/* Change var to its typename equivalent */
	if (isupper(var[0]))
		strcpy(typename, "uc_");
	else
		strcpy(typename, "lc_");
	strcat(typename, var);

	/* Search the Typedef Linked list for instance of 'typename'
	   using functions defined in TYPEDEF_FUNCTIONS.H
	   If 'typename' is present, return the TYPE_NAME token,
	   Otherwise, return the IDENTIFIER token.
	*/
	if (traverse_types(typename) == YES)
	{
		yylval.id = malloc(strlen(yytext)+1);
		strcpy(yylval.id, yytext);
		return TYPEDEF_NAME;
	}
	else
	{
		yylval.id = malloc(strlen(yytext)+1);
		strcpy(yylval.id, yytext);
		return IDENTIFIER;
	}
}
