name: ECLiPSe Prolog regression tests

on: push

jobs:
  run-prolog:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ECLiPSe Prolog
      run: |
        .\.github\workflows\ECLiPSe_7.1_13_x86_64_nt.exe /S
        # curl -O https://eclipseclp.org/Distribution/Builds/7.1_13/x86_64_nt/ECLiPSe_7.1_13_x86_64_nt.exe
        # .\ECLiPSe_7.1_13_x86_64_nt.exe.exe /S

    - name: Add ptc_solver to ECLiPSe Prolog
      run: |
        cp ".\\.github\\workflows\\ptc_solver\\*" "C:\\Program Files\\ECLiPSe 7.1\\lib\\"

    - name: Write hello world from ECLiPSe Prolog
      run: |
        eclipse -f "writeln(\"Hello world from ECLiPSe Prolog\n\")."

