name: ECLiPSe Prolog regression tests

on: push

jobs:
  run-prolog:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ECLiPSe Prolog
      run: |
        .\.github\workflows\ECLiPSe_7.1_13_x86_64_nt.exe /S
        dir "C:\\Program Files\\"

    - name: Add ptc_solver to ECLiPSe Prolog
      run: |
        cp ".\\.github\\workflows\\ptc_solver\\*" "C:\\Program Files (x86)\\ECLiPSe 7.1\\lib\\"

    - name: Write hello world from ECLiPSe Prolog
      run: |
        eclipse -f "writeln(\"Hello world from ECLiPSe Prolog\n\")."

